### ISSUE TITLE
Handle multiple injectors for load tests

### ISSUE THREAD

**Issue by geraldpereira** [OctoPerf/kraken#29]
~~Not necessarily useful for debugging.~~

~~Solution 1 (OctoPerf like): an agent is started on each injector, it can start Gatling (internally or as a sibling Docker image ?).~~

Solution 2: use ~~docker swarm or~~ kubernetes

Compatibility with a simple Docker installation (no multi injectors) should be kept.

**Comment by geraldpereira** [comment]
# Storage-synchronizer

We cannot share a host folder on K8s, files synchronizing must be done differently.

- [ ] share a docker volume between the injector/har importer and a storage-synchronizer container
- [ ] wait for files download before running (see rendez-vous)
- [ ] download all data using storage-client on start
- [ ] report modifications using storage-client during execution (uni-directional sync -> storage-file)
- [ ] filter folder to be synchronized (i.e. results + simulations + resources folders for har-import, results without the gatling.log folder for gatling-debug)

# Rendez-vous

- [ ] A single load injector (kraken-gatling container) / har importer must wait for its sibling storage-synchronizer container to have downloaded its files before executing. 
- [ ] Injectors must wait for everyone to be ready before starting the load test (images must be pulled, files must be downloaded).
- [ ] One rendezVousId for each run, shared by all containers started
- [ ] Compute the number of required containers beforehand
- [ ] Endpoint to wait for everyone to be ready: SSE or polling?

# task-runner

One interface to run tasks (run a load test, debug a load test, import an HAR file), two implementations: Docker and K8s

- [ ] Remove Shell command executor
- [ ] Remove Docker command executor
- [ ] Simplify the current shell scripts => move all that can be moved to each docker container runner.sh file
- [ ] List containers: returns the list of all containers relevant for a task execution
- [ ] one endpoint for each specific task
