### ISSUE TITLE
Add keyboard shortcuts for the Result panel

### ISSUE THREAD

**Issue by geraldpereira** [OctoPerf/kraken#38]
## All selectable tables

- [x] Handle the focus on the Result table `tabindex=0` (it is currently handled for storage trees, should we handle it at the tab level ?)
- [x] Up to select the previous item
- [x] Down to select the next item
- [x] CTRL + Menu item click on delete to skip confirmation dialog

## Result table
- [x] SUPPR to remove the selected result
- [x] CTRL + SUPPR to remove the selected result (no confirmation dialog)
- [x] ENTER to open the selected result Grafana report (if available)

## Debug table
- [x] ENTER to open the comparison dialog
- [ ] Add loading state

## Task table
- [x] SUPPR to cancel/remove the selected task
- [x] CTRL + SUPPR to cancel/remove the selected task (no confirmation dialog)
